export const MOCK_TELEMETRY = {
  refrigerator: {
    id: 'refrigerator',
    name: 'Buzdolabı',
    room: 'Mutfak',
    status: 'online',
    lastUpdated: '1 dakika önce',
    currentPower: 85,
    todayConsumption: 1.84,
    monthlyConsumption: 55.2,
    estimatedCost: 26.2,
    efficiencyRating: 'A+++',
    peakTime: '12:00 - 14:00',
    aiRecommendation: 'Optimal Soğutma: İç sıcaklık 3.2°C olarak sabit. Haftalık tüketim ortalamanın %4 altında.',
    healthScore: 100,
    temperature: 3.2,
    anomalies: [],
    maintenancePrediction: 'Gelecek 12 ay bakım gerektirmiyor',
    historyData: [
      { time: '08:00', value: 80 },
      { time: '10:00', value: 85 },
      { time: '12:00', value: 110 },
      { time: '14:00', value: 90 },
      { time: '16:00', value: 85 },
      { time: '18:00', value: 85 },
      { time: '20:00', value: 80 }
    ],
  },
  oven: {
    id: 'oven',
    name: 'Fırın & Ocak',
    room: 'Mutfak',
    status: 'offline',
    lastUpdated: '10 dakika önce',
    currentPower: 0,
    todayConsumption: 1.45,
    monthlyConsumption: 43.5,
    estimatedCost: 20.6,
    efficiencyRating: 'A',
    peakTime: '18:00 - 19:30',
    aiRecommendation: 'Konveksiyon modu: Pişirme süresini 15 dakika kısaltarak 0.25 kWh tasarruf sağlandı.',
    healthScore: 95,
    temperature: 22,
    anomalies: [],
    maintenancePrediction: 'Isıtma elemanları 6 ay içinde kontrol edilmeli',
    historyData: [
      { time: '08:00', value: 0 },
      { time: '10:00', value: 0 },
      { time: '12:00', value: 0 },
      { time: '14:00', value: 0 },
      { time: '16:00', value: 0 },
      { time: '18:00', value: 2400 },
      { time: '20:00', value: 0 }
    ],
  },
  television: {
    id: 'television',
    name: 'Televizyon',
    room: 'Oturma Odası',
    status: 'online',
    lastUpdated: '5 dakika önce',
    currentPower: 110,
    todayConsumption: 1.15,
    monthlyConsumption: 34.5,
    estimatedCost: 16.4,
    efficiencyRating: 'A+',
    peakTime: '19:00 - 22:30',
    aiRecommendation: 'Akıllı Karartma: Parlaklığı ortam ışığına ayarlamak anlık 15W tasarruf sağlar.',
    healthScore: 98,
    temperature: 34,
    anomalies: [],
    maintenancePrediction: 'Sistem durumu mükemmel',
    historyData: [
      { time: '08:00', value: 0 },
      { time: '10:00', value: 0 },
      { time: '12:00', value: 110 },
      { time: '14:00', value: 110 },
      { time: '16:00', value: 0 },
      { time: '18:00', value: 110 },
      { time: '20:00', value: 115 }
    ],
  },
  computer: {
    id: 'computer',
    name: 'Bilgisayar',
    room: 'Çalışma Odası',
    status: 'online',
    lastUpdated: '12 dakika önce',
    currentPower: 145,
    todayConsumption: 1.68,
    monthlyConsumption: 50.4,
    estimatedCost: 24.0,
    efficiencyRating: 'A',
    peakTime: '09:00 - 17:00',
    aiRecommendation: 'Güç Tasarrufu: Otomatik uyku modu aktif. Ekran parlaklığı %70 yapıldığında 12W güç kancası önlenir.',
    healthScore: 100,
    temperature: 42,
    anomalies: [],
    maintenancePrediction: 'Termal macun kontrolü 8 ay sonra',
    historyData: [
      { time: '08:00', value: 50 },
      { time: '10:00', value: 150 },
      { time: '12:00', value: 145 },
      { time: '14:00', value: 155 },
      { time: '16:00', value: 140 },
      { time: '18:00', value: 80 },
      { time: '20:00', value: 50 }
    ],
  }
};
